[project]
name = "mcp-for-mcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.121.1",
    "fastmcp>=3.0.0b1",
    "toon-format==0.9.0b1",
]
